version: '3.1'

services:
  db:
    image: mysql
    container_name: mealmatedb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - mealmate-network

  app:
    image: junseok1204/mealmate-0.0.1-snapshot
    container_name: app-container
    ports:
      - 8080:8080
    env_file:
      - "./.env"
    environment:
      - TZ=Asis/Seoul
    depends_on:
      - db
    links:
      - db
    networks:
      - mealmate-network
    restart: always

  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    container_name: mealmate-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - mealmate-network

  certbot:
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    networks:
      - mealmate-network
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  mealmate-network:

volumes:
  mysql-data: