name: Java Chcek Code Style with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Checkstyle
        run: ./gradlew checkstyleMain